Accessibility Dropdown Fixes
onc-healthit/lantern-back-end pull request #316
Opened 2022-09-28 20:09 UTC by emichaud998

Pull requests into this repository require the following checks to be completed by the submitter and reviewers.

Changes in this PR:
- Moved the "Select All" and "Deselect All" buttons outside of the FHIR version dropdown since it was not possible to tab to the buttons within the dropdown
- Changed colors of dropdowns and buttons to make them stand out more
- Change the aria labels of all of the dropdowns to better explain how to use and navigate them

**Submitter:**
- [ ] Administrative tasks are complete.
  - This pull request describes why these changes were made.
  - The JIRA ticket links to this PR.
  - The JIRA ticket for this PR is: [Lantern 518 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-518)
- [ ] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.
- [ ] Code review has been performed.
  - Code diff has been done and checked to ensure only expected code is being committed.
  - A linter for the language has been run.

**Primary Reviewer:**

- [ ] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [ ] Code review has been performed.
  - Code is maintainable, reusable, efficient, and correct.
  - Code accomplishes the tasks purpose.
  - Code follows style guidance appropriate for the language, including passing linter checks.
  - Code is well commented (which does not mean verbosely commented).
- [ ] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.

**Merger:**

Prior to merging, ensure that all checks have been completed. Delete the branch after the merge
is complete.

2022-10-12 14:48 UTC, bmath10 requested changes
This also needs a rebase!

2022-10-12 14:48 UTC, bmath10 commented on shinydashboard/lantern/ui.R
> +                  selectInputNode.setAttribute('aria-label', 'Use the arrow keys to naviate the filter menu.')
misspelling: "navigate"

2022-10-12 14:48 UTC, bmath10 commented on shinydashboard/lantern/ui.R
> +                selectDropdown.setAttribute('aria-label', 'Use the arrow keys to naviate the filter menu.')
same as above: "navigate"

2022-10-12 14:48 UTC, bmath10 commented on shinydashboard/lantern/ui.R
> +              selectInput.setAttribute('aria-label', 'Use the arrow keys to naviate the filter menu.')
same as above

2022-10-12 14:48 UTC, bmath10 commented on shinydashboard/lantern/ui.R
> +              dropDownButton.setAttribute('aria-label', 'Dropdown filter menu button. Press the down arrow key to open the filter menu, use the tab or arrow keys to navigate through options, press en
Is it possible to just have this read out when you're on the dropdown without it being open? I tried navigating with VoiceOver and it was kind of a lot to have this read every time you switched options for the dropdown. If this is the only way to do it then I think it's fine, but just wanted to ask and see if there was an alternative!

2022-10-14 17:02 UTC, bmath10 commented
Once this is rebased I can merge it in!

2022-10-17 17:25 UTC, bmath10 commented
This is kind of a weird bug (maybe due to the rebase?) but when I first load the dashboard, the "Skip Past Resources" on the Resources page is just floating above the FHIR Version dropdown buttons. Once I refresh the page, though, it disappears and only shows up where it's expected above the resources select object.

2022-10-17 22:00 UTC, emichaud998 commented
> This is kind of a weird bug (maybe due to the rebase?) but when I first load the dashboard, the "Skip Past Resources" on the Resources page is just floating above the FHIR Version dropdown buttons. Once I refresh the page, though, it disappears and only shows up where it's expected above the resources select object.

Weird I am not seeing this, I tried it both by booting Lantern up using R shiny and opening it up in the browser from there, and I also tried it by going to localhost:3838, but I am not seeing the Skip to Content floating there

2022-10-18 15:17 UTC, merged